onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp
  - unrs-resolver

overrides:
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  next@>=10.0.0 <15.5.10: '>=15.5.10'
  next@>=15.5.0-canary.0 <15.5.7: '>=15.5.7'
  next@>=15.5.1-canary.0 <15.5.10: '>=15.5.10'
  next@>=15.5.1-canary.0 <15.5.8: '>=15.5.8'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
